export default {
  PRIMARY_COLOR: '#6B46E5',
  PRIMARY_LIGHT_COLOR: '#886AEA',

  WARNING_COLOR: '#E67E00',
  RED_COLOR: '#FF0000',
  GREEN_COLOR: '#008000',
  WHITE_COLOR: '#FFFFFF',
  WHITE_LIGHTER_COLOR: '#f5f5f5',
  WHITE_LIGHT_COLOR: '#ffffffb5',
  BLACK_COLOR: '#333333',
  RED_BACKGROUND_COLOR: '#F8D3D6',

  LIGHT_COLOR: '#CCD2D9',
  GRAY_COLOR: '#808080',
  GRAY_DARK_COLOR: '#DDD',
  GRAY_DARKER_COLOR: '#BBB',

  FONT_SIZE_TINY: 10,
  FONT_SIZE_MEDIUM: 12,
  FONT_SIZE_LARGE: 14,
  FONT_SIZE_SUPPER_LARGE: 16,

  LINE_HEIGHT_TINY: 10,
  LINE_HEIGHT_MEDIUM: 16,
  LINE_HEIGHT_LARGE: 20,
  LINE_HEIGHT_SUPPER_LARGE: 22,

  FONT_WEIGHT_LIGHT: '200',
  FONT_WEIGHT_MEDIUM: '400',
  FONT_WEIGHT_BOLD: '500',
  FONT_WEIGHT_SUPPER_BOLD: '700',

  BTN_PADDING_HORIZONTAL: 16,
  BTN_PADDING_VERTICAL: 12,
  BTN_BORDER_RADIUS: 40,
  BTN_BORDER_WIDTH: 2,

  PADDING_HORIZONTAL: 16,
  PADDING_VERTICAL: 16,
};
